### ISSUE TITLE
Setting sensor values

### ISSUE THREAD

**Issue by SanderM2** [ridiekel/jeletask#7]
You wrote "You can only listen to sensor values." in the manual. But for airco and aurus wall switches there's a set function to set temperature, auto/heat/cool/dry/cool mode etc.. So we need a way to set the sensor values too.

It's documented on page 5 of the teletask pdf.

Any plans on implementing this?

**Comment by ridiekel** [comment]
In theory, if the DOIP protocol supports it, we can implement it. I will put this in the backlog as enhancement.

**Comment by SanderM2** [comment]
Is this something you're actively working on, expecting a new release soon?
Or is this something that will take a while?

I'm actually waiting for a new release from you. If it's something that will take a whil I'm going to make quick patches for my own installation so I can make it all work with HA while waiting for an updates version of 'jeletask'

**Comment by ridiekel** [comment]
I have been working on the motor issue, since that has some more users waiting for it. The solution is basically the same though, so I expect the sensors to work as soon as the motor position enhancement is in place. It might be a couple of weeks though. I have limited time available, so going as fast as possible. Motor solution is almost ready.
Did also make the decision to drop the micros support, which makes it somewhat less complicated.

**Comment by SanderM2** [comment]
Hi ridiekel, good to hear. If it's only a couple of weeks I'm going to wait.
Thanks! ;)

**Comment by Borrellio** [comment]
I need this feature too. Without it I cannot control my heatpump. 

Thanks for the good work already!

**Comment by SanderM2** [comment]
I have implemented this in this PR: https://github.com/ridiekel/jeletask/pull/18
